default_stages: [pre-commit]
exclude: '^README.md'
repos:
- repo: http://github.com/antonbabenko/pre-commit-terraform
  rev: v1.73.0
  hooks:
  - id: terraform_fmt
  - id: terraform_validate
  - id: terraform_tflint
  - id: terraform_trivy
    args: ['--severity', 'HIGH,CRITICAL']
  - id: terraform_checkov
    args: ['--config-file', '.checkov.yaml']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: whitespace-fixer
  - id: check-added-large-files
  - id: detect-private-keys
  - id: check-merge-conflicts
  - id: check-json
  - id: check-toml
  - id: no-commit-to-branch
    args: ['--branch', 'main', '--branch', 'master']
  - id: pretty-format-json
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.6
  hooks:
  - id: ruff
  - id: ruff-fix
