[project]
name = "terraform-dms-module"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "backports-tarfile>=1.2.0",
    "etl-manager>=9.0.1",
    "moto>=5.1.19",
    "oracledb>=3.4.1",
]
