name: prek-like-ci-cd

on:
  pull_request:

jobs:
  prek:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      # Pull modules and such, so pre-commit does not fail
      - name: Terraform init
        run: terraform init -input=false

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Manual Trivy Setup
        uses: aquasecurity/setup-trivy@v0.2.0
        with:
          cache: true
          version: v0.65.0

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          skip-dirs: .terraform,examples
          install-only: true
          skip-setup-trivy: true

      - name: Install checkov
        run: pip install --upgrade pip checkov

      - name: Install prek
        run: pip install prek

      - name: Cache prek
        uses: actions/cache@v4
        with:
          path: ~/.cache/prek
          key: prek-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            prek-

      - name: Run prek
        run: prek run --all-files
